code/wfedu/GuLiEdu/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
import xadmin
from users.views import index

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^orgs/', include('orgs.urls', namespace='orgs')),
    url(r'^operations/', include('operations.urls', namespace='operations')),
    url(r'^$',index,name='index')
]

handler404 = 'users.views.handler_404'
handler500 = 'users.views.handler_500'

code/wfedu/apps/courses/urls.py
from django.conf.urls import url
from .views import course_list,course_detail,course_video,course_comment
urlpatterns = [
    url(r'^course_list/$',course_list,name='course_list'),
    url(r'^course_detail/(\d+)/$', course_detail, name='course_detail'),
    url(r'^course_video/(\d+)/$', course_video, name='course_video'),
    url(r'^course_comment/(\d+)/$', course_comment, name='course_comment'),
]

code/wfedu/apps/operations/urls.py
from django.conf.urls import url
from .views import user_ask,user_love,user_comment,user_deletelove
urlpatterns = [
    url(r'^user_ask/$',user_ask,name='user_ask'),
    url(r'^user_love/$',user_love,name='user_love'),
    url(r'^user_deletelove/$',user_deletelove,name='user_deletelove'),
    url(r'^user_comment/$', user_comment, name='user_comment')
]

code/wfedu/apps/orgs/urls.py
from django.conf.urls import url
from .views import org_list,org_detail,org_detail_course,org_detail_desc,org_detail_teacher,teacher_list,teacher_detail

urlpatterns = [
    url(r'^org_list/$',org_list,name='org_list'),
    url(r'^org_detail/(\d+)/$', org_detail, name='org_detail'),
    url(r'^org_detail_course/(\d+)/$', org_detail_course, name='org_detail_course'),
    url(r'^org_detail_desc/(\d+)/$', org_detail_desc, name='org_detail_desc'),
    url(r'^org_detail_teacher/(\d+)/$', org_detail_teacher, name='org_detail_teacher'),

    url(r'^teacher_list/$',teacher_list,name='teacher_list'),
    url(r'^teacher_detail/(\d+)/$', teacher_detail, name='teacher_detail'),
]

code/wfedu/apps/users/urls.py
from django.conf.urls import url
from .views import user_register,UserLoginView,user_logout,user_active,user_forget,user_reset,user_info,user_changeimage,user_changeinfo,user_changeemail,user_resetemail,user_course,user_loveteacher,user_loveorg,user_lovecourse,user_message,user_deletemessage
urlpatterns = [
    url(r'^user_register/$',user_register,name='user_register'),
    url(r'^user_login/$', UserLoginView.as_view(), name='user_login'),
    url(r'^user_logout/$', user_logout, name='user_logout'),
    url(r'^user_active/(\w+)/$', user_active, name='user_active'),

    url(r'^user_forget/$', user_forget, name='user_forget'),
    url(r'^user_reset/(\w+)/$', user_reset, name='user_reset'),

    url(r'^user_info/$',user_info,name='user_info'),

    url(r'^user_changeimage/$',user_changeimage,name='user_changeimage'),
    url(r'^user_changeinfo/$', user_changeinfo, name='user_changeinfo'),
    url(r'^user_changeemail/$',user_changeemail,name='user_changeemail'),
    url(r'^user_resetemail/$', user_resetemail, name='user_resetemail'),

    url(r'^user_course/$',user_course,name='user_course'),
    url(r'^user_loveorg/$', user_loveorg, name='user_loveorg'),
    url(r'^user_loveteacher/$', user_loveteacher, name='user_loveteacher'),
    url(r'^user_lovecourse/$', user_lovecourse, name='user_lovecourse'),

    url(r'^user_message/$', user_message, name='user_message'),
    url(r'^user_deletemessage/$', user_deletemessage, name='user_deletemessage'),

]

code/wfedu/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

code/wfedu/apps/courses/models.py
from django.db import models
from datetime import datetime
from orgs.models import OrgInfo,TeacherInfo
# Create your models here.
class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/',max_length=200,verbose_name="课程封面")
    name = models.CharField(max_length=20,verbose_name="课程名称")
    study_time = models.IntegerField(default=0,verbose_name="学习时长")
    study_num = models.IntegerField(default=0,verbose_name="学习人数")
    level = models.CharField(choices=(('gj','高级'),('zj','中级'),('cj','初级')),max_length=5,verbose_name="课程 难度",default='cj')
    love_num = models.IntegerField(default=0,verbose_name="收藏数")
    click_num = models.IntegerField(default=0,verbose_name="访问量")
    desc = models.CharField(max_length=200,verbose_name="课程简介")
    detail = models.TextField(verbose_name="课程详情")
    category = models.CharField(choices=(('qd','前端开发'),('hd','后端开发')),verbose_name="课程类别",max_length=5)
    course_notice = models.CharField(max_length=200,verbose_name="课程公告")
    course_need = models.CharField(max_length=100,verbose_name="课程须知")
    teacher_tell = models.CharField(max_length=100,verbose_name="老师教导")
    orginfo = models.ForeignKey(OrgInfo,verbose_name="所属机构")
    teacherinfo = models.ForeignKey(TeacherInfo,verbose_name="所属讲师")
    is_banner = models.BooleanField(default=False,verbose_name="是否轮播")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程信息'
        verbose_name_plural = verbose_name

class LessonInfo(models.Model):
    name = models.CharField(max_length=50,verbose_name="章节名称")
    courseinfo = models.ForeignKey(CourseInfo,verbose_name="所属课程")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '章节信息'
        verbose_name_plural = verbose_name


class VideoInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name="视频名称")
    study_time = models.IntegerField(default=0,verbose_name="视频时长")
    url = models.URLField(default='http://www.atguigu.com',verbose_name="视频链接",max_length=200)
    lessoninfo = models.ForeignKey(LessonInfo,verbose_name="所属章节")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '视频信息'
        verbose_name_plural = verbose_name


class SourceInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name="资源名称")
    down_load = models.FileField(upload_to='source/',max_length=200,verbose_name="下载路径")
    courseinfo = models.ForeignKey(CourseInfo,verbose_name="所属课程")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '资源信息'
        verbose_name_plural = verbose_name

code/wfedu/apps/orgs/models.py
from django.db import models
from datetime import datetime
from DjangoUeditor.models import UEditorField
# Create your models here.
class CityInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="城市名称")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '城市信息'
        verbose_name_plural = verbose_name


class OrgInfo(models.Model):
    image = models.ImageField(upload_to='org/',max_length=200,verbose_name="机构封面")
    name = models.CharField(max_length=20,verbose_name="机构名称")
    course_num = models.IntegerField(default=0,verbose_name="课程数")
    study_num = models.IntegerField(default=0,verbose_name="学习人数")
    address = models.CharField(max_length=200,verbose_name="机构地址")
    desc = models.CharField(max_length=200,verbose_name="机构简介")
    detail = UEditorField(verbose_name='机构详情',
	                         width=700,
	                         height=400,
	                         toolbars='full',
	                         imagePath='ueditor/images/',
	                         filePath='ueditor/files/',
	                         upload_settings={'imageMaxSizing':1024000},
	                         default='')

    love_num = models.IntegerField(default=0,verbose_name="收藏数")
    click_num = models.IntegerField(default=0,verbose_name="访问量")
    category = models.CharField(choices=(('pxjg','培训机构'),('gx','高校'),('gr','个人')),max_length=10,verbose_name="机构类别")
    cityinfo = models.ForeignKey(CityInfo,verbose_name="所在城市")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机构信息'
        verbose_name_plural = verbose_name


class TeacherInfo(models.Model):
    image = models.ImageField(upload_to='teacher/', max_length=200, verbose_name="讲师头像")
    name = models.CharField(max_length=20,verbose_name="讲师姓名")
    work_year = models.IntegerField(default=3,verbose_name="工作年限")
    work_position = models.CharField(max_length=20,verbose_name="工作职位")
    work_style = models.CharField(max_length=20,verbose_name="教学特点")
    work_company = models.ForeignKey(OrgInfo,verbose_name="所属机构")
    age = models.IntegerField(default=30,verbose_name="讲师年龄")
    gender = models.CharField(choices=(('boy','男'),('girl','女')),max_length=10,verbose_name="讲师性别",default='boy')
    love_num = models.IntegerField(default=0, verbose_name="收藏数")
    click_num = models.IntegerField(default=0, verbose_name="访问量")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '讲师信息'
        verbose_name_plural = verbose_name


code/wfedu/apps/orgs/views.py
from django.shortcuts import render
from .models import OrgInfo,TeacherInfo,CityInfo
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from operations.models import UserLove
from django.db.models import Q

# Create your views here.

def org_list(request):
    all_orgs = OrgInfo.objects.all()
    all_citys = CityInfo.objects.all()
    sort_orgs = all_orgs.order_by('-love_num')[:3]

    #全局搜索功能的过滤
    keyword = request.GET.get('keyword','')
    if keyword:
        all_orgs = all_orgs.filter(Q(name__icontains=keyword)|Q(desc__icontains=keyword)|Q(detail__icontains=keyword))

    #按照机构类别进行过滤筛选
    cate = request.GET.get('cate','')
    if cate:
        all_orgs = all_orgs.filter(category=cate)

    #按照所在地区进行过滤筛选
    cityid = request.GET.get('cityid','')
    if cityid:
        all_orgs = all_orgs.filter(cityinfo_id=int(cityid))

    #排序
    sort = request.GET.get('sort','')
    if sort:
        all_orgs = all_orgs.order_by('-'+sort)


    #分页功能
    pagenum = request.GET.get('pagenum','')
    pa = Paginator(all_orgs,3)
    try:
        pages = pa.page(pagenum)
    except PageNotAnInteger:
        pages = pa.page(1)
    except EmptyPage:
        pages = pa.page(pa.num_pages)


    return render(request,'orgs/org-list.html',{
        'all_orgs':all_orgs,
        'pages':pages,
        'all_citys':all_citys,
        'sort_orgs':sort_orgs,
        'cate':cate,
        'cityid':cityid,
        'sort':sort,
        'keyword':keyword
    })

def org_detail(request,org_id):
    if org_id:
        org = OrgInfo.objects.filter(id = int(org_id))[0]

        org.click_num += 1
        org.save()



        #在返回页面数据的时候，需要返回收藏这个机构的状态，根据状态让模板页面显示收藏还是取消收藏。而不能让页面固定显示收藏。
        lovestatus = False
        if request.user.is_authenticated():
            love = UserLove.objects.filter(love_man=request.user,love_id=int(org_id),love_type=1,love_status=True)
            if love:
                lovestatus = True


        return render(request,'orgs/org-detail-homepage.html',{
            'org':org,
            'detail_type':'home',
            'lovestatus':lovestatus
        })

def org_detail_course(request,org_id):
    if org_id:
        org = OrgInfo.objects.filter(id = int(org_id))[0]
        all_courses = org.courseinfo_set.all()

        lovestatus = False
        if request.user.is_authenticated():
            love = UserLove.objects.filter(love_man=request.user, love_id=int(org_id), love_type=1, love_status=True)
            if love:
                lovestatus = True

        # 分页功能
        pagenum = request.GET.get('pagenum', '')
        pa = Paginator(all_courses,2)
        try:
            pages = pa.page(pagenum)
        except PageNotAnInteger:
            pages = pa.page(1)
        except EmptyPage:
            pages = pa.page(pa.num_pages)
        return render(request,'orgs/org-detail-course.html',{
            'org':org,
            'pages':pages,
            'detail_type': 'course',
            'lovestatus':lovestatus
        })


def org_detail_desc(request,org_id):
    if org_id:
        org = OrgInfo.objects.filter(id = int(org_id))[0]

        lovestatus = False
        if request.user.is_authenticated():
            love = UserLove.objects.filter(love_man=request.user, love_id=int(org_id), love_type=1, love_status=True)
            if love:
                lovestatus = True

        return render(request,'orgs/org-detail-desc.html',{
            'org':org,
            'detail_type': 'desc',
            'lovestatus':lovestatus
        })

def org_detail_teacher(request,org_id):
    if org_id:
        org = OrgInfo.objects.filter(id = int(org_id))[0]

        lovestatus = False
        if request.user.is_authenticated():
            love = UserLove.objects.filter(love_man=request.user, love_id=int(org_id), love_type=1, love_status=True)
            if love:
                lovestatus = True

        return render(request,'orgs/org-detail-teachers.html',{
            'org':org,
            'detail_type': 'teacher',
            'lovestatus':lovestatus
        })


def teacher_list(request):
    all_teachers = TeacherInfo.objects.all()
    sort_teachers = all_teachers.order_by('-love_num')[:2]

    # 全局搜索功能的过滤
    keyword = request.GET.get('keyword', '')
    if keyword:
        all_teachers = all_teachers.filter(name__icontains=keyword)

    sort = request.GET.get('sort','')
    if sort:
        all_teachers = all_teachers.order_by('-'+sort)


    pagenum = request.GET.get('pagenum', '')
    pa = Paginator(all_teachers, 2)
    try:
        pages = pa.page(pagenum)
    except PageNotAnInteger:
        pages = pa.page(1)
    except EmptyPage:
        pages = pa.page(pa.num_pages)

    return render(request,'orgs/teachers-list.html',{
        'all_teachers':all_teachers,
        'sort_teachers':sort_teachers,
        'pages':pages,
        'sort':sort,
        'keyword':keyword
    })

def teacher_detail(request,teacher_id):
    if teacher_id:
        all_teachers = TeacherInfo.objects.all()
        teacher = TeacherInfo.objects.filter(id = int(teacher_id))[0]
        sort_teachers = all_teachers.order_by('-love_num')[:2]

        teacher.click_num += 1
        teacher.save()

        loveteacher = False
        loveorg = False
        if request.user.is_authenticated():
            love = UserLove.objects.filter(love_id=int(teacher_id), love_type=3, love_status=True, love_man=request.user)
            if love:
                loveteacher = True
            love1 = UserLove.objects.filter(love_id=teacher.work_company.id, love_type=1, love_status=True,
                                            love_man=request.user)
            if love1:
                loveorg = True

        return render(request,'orgs/teacher-detail.html',{
            'teacher':teacher,
            'sort_teachers':sort_teachers,
            'loveteacher':loveteacher,
            'loveorg':loveorg
        })

code/wfedu/templates/orgs/org-detail-base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block mycss %}
   <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block mycss1 %}{% endblock %}
{% endblock %}

{% block middle %}
    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ org.image }}"/>
            <div class="head fl">
                <h1>
                    {{ org.name }}
                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin" data-favid="22" data-fav-type="1" id="love">
                 {% if lovestatus %}取消收藏{% else %}收藏{% endif %}
            </div>

        </div>
    </div>
{% endblock %}

{% block content %}
    <section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="/">首页</a>></li>
			<li><a href="{% url 'orgs:org_list' %}">课程机构</a>></li>
			<li>{% block breach %}{% endblock %}</li>
		</ul>
	</div>
</section>
    <section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li {% if detail_type == 'home' %}class="active2"{% endif %}><a href="{% url 'orgs:org_detail' org.id %}">机构首页</a></li>
                <li {% if detail_type == 'course' %}class="active2"{% endif %}><a href="{% url 'orgs:org_detail_course' org.id %}">机构课程</a></li>
                <li {% if detail_type == 'desc' %}class="active2"{% endif %}><a href="{% url 'orgs:org_detail_desc' org.id %}">机构介绍</a></li>
                <li {% if detail_type == 'teacher' %}class="active2"{% endif %}><a href="{% url 'orgs:org_detail_teacher' org.id %}">机构讲师</a></li>
			</ul>
		</div>
        {% block right %}

        {% endblock %}
    </div>
</section>
{% endblock %}

{% block footer %}{% endblock %}


{% block myjs %}
    <script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
    <script type="text/javascript">
$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static 'images/' %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('#love').click(function () {
        var loveid = {{ org.id }};
        var lovetype = 1;
        $.ajax({
            type:'GET',
            url:'{% url 'operations:user_love' %}',
            data:{
                loveid:loveid,
                lovetype:lovetype
            },
            success:function (callback) {
                if(callback.status == 'ok'){
                    $('#love').text(callback.msg)
                }else if(callback.status == 'nologin'){
                    window.location.href = '{% url 'users:user_login' %}';
                } else {
                    alert(callback.msg)
                }
            }
        })
    })
})
</script>
    {% block myjs1 %}{% endblock %}
{% endblock %}




code/wfedu/templates/orgs/org-detail-desc.html
{% extends 'orgs/org-detail-base.html' %}
{% block title %}机构介绍{% endblock %}
{% block breach %}机构介绍{% endblock %}
{% block right %}
    <div class="right companycenter layout" >
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">

            <p>{{ org.detail|safe }}</p>

        </div>
    </div>
{% endblock %}

code/wfedu/templates/orgs/org-detail-teachers.html
{% extends 'orgs/org-detail-base.html' %}
{% block title %}机构教师{% endblock %}
{% block breach %}机构教师{% endblock %}
{% block right %}
    <div class="right companycenter layout" >
        <div class="head">
            <h1>机构讲师</h1>
        </div>
        <div class="messagelist">
            <div class=" butler_list butler-fav-box">
                {% for teacher in org.teacherinfo_set.all %}
                <dl class="des users">
                    <dt>
                        <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                        <img width="100" height="100" class="scrollLoading" data-url="{{ MEDIA_URL }}{{ teacher.image }}"/>
                        </a>
                    </dt>
                    <dd>
                        <h1>
                            <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                            {{ teacher.name }}<span class="key">已认证</span>
                            </a>
                        </h1>
                        <ul class="cont clearfix">
                            <li class="time">工作年限：<span>{{ teacher.work_year }}年</span></li>
                            <li class="c7">课程数：<span>{{ teacher.courseinfo_set.count }}</span></li>
                        </ul>
                    </dd>
                </dl>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

code/wfedu/templates/orgs/teacher-detail.html
{% extends 'base.html' %}
{% block title %}讲师详情 - 谷粒教育网{% endblock %}
{% block content %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'orgs:teacher_list' %}">授课讲师</a>></li>
                <li>讲师详情</li>
            </ul>
        </div>
    </section>
    <section>
	<div class="wp butler-detail-box butler-diaryd-box clearfix">
        <div class="fl list">
            <div class="butler_detail_list clearfix">
                <div class="brief">
                    <dl class="des">
                        <dt>
                            <div class="picpic">
                                <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                            </div>
                            <div class="btn">
                                <span class="fl btn1 collectionbtn" id="jsLeftBtn">
                                     {% if loveteacher %}取消收藏{% else %}收藏{% endif %}
                                </span>
                                <span class="fr btn2 shareBtn bdsharebuttonbox">
                                    <span class="fl">分享</span>
                                    <a href="#" class="bds_more" data-cmd="more"></a>
                                </span>
                            </div>
                        </dt>
                        <dd>
                            <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                <h1>{{ teacher.name }}<span class="key picbig">金牌讲师</span></h1>
                            </a>
                            <ul class="cont">
                                <li>工作年限：<span>{{ teacher.work_year }}年</span></li>
                                <li>就职公司：<span>{{ teacher.work_company.name }}</span></li>
                                <li>工作职位：<span>{{ teacher.work_position }}&nbsp;</span></li>
                                <li>教学特点：<span>{{ teacher.work_style }}</span></li>
                            </ul>
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="butler_detail_cont clearfix">
                <div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active"><a href="{% url 'courses:course_list' %}">全部课程</a> </li>
					</ul>
				</div>
                    <div class="companycenter">
                        <div class="group_list brief">
                        {% for course in teacher.courseinfo_set.all %}
                            <div class="module1_5 box">
                                <a href="{% url 'courses:course_detail' course.id %}">
                                    <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                    <span class="fl">时长：<i class="key">{{ course.study_time }}</i></span>
                                    <span class="fr">学习人数：{{ course.study_num }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl">{{ course.orginfo.name }}</span>
                                    <span class="star fr  notlogin" data-favid="15">{{ course.love_num }}</span>
                                </div>
                            </div>
                        {% endfor %}
                        </div>
                    </div>
                <!--<div class="pageturn">-->
                    <!--<ul class="pagelist">-->
                        <!--<li class="active"><a href="?page=1">1</a></li>-->
                    <!--</ul>-->
                <!--</div>-->
            </div>
            </div>
        </div>
        <div class="fr list">
             <div class="butler_detail_list">
                <div class="right butler-company-box">
                <div class="head">
                    <h1>{{ teacher.work_company.name }}</h1>
                    <p>{{ teacher.work_company.desc }}</p>
                </div>
                <div class="pic">
                    <a href="{% url 'orgs:org_detail' teacher.work_company.id %}">
                        <img width="150" height="80" src="{{ MEDIA_URL }}{{ teacher.work_company.image }}"/>
                    </a>
                </div>
                <a href="{% url 'orgs:org_detail' teacher.work_company.id %}">
                    <h2 class="center">{{ teacher.work_company.name }}</h2>
                </a>
                <p class="center tell">地址：{{ teacher.work_company.address }}</p>
                <a class="btn" id="jsRightBtn">{% if loveorg %}取消收藏{% else %}收藏{% endif %}</a>
            </div>
            </div>
            <div class="butler_detail_cont">
                <div class="butler_list_box">
                    <div class="right layout">
                        <div class="head">讲师排行榜</div>
                        {% for teacher1 in sort_teachers %}
                        <dl class="des">
                            <span class="num fl">{{ forloop.counter }}</span>
                            <a href="{% url 'orgs:teacher_detail' teacher1.id %}">
                                <dt>
                                    <img width="50" height="50" class="scrollLoading" src="{{ MEDIA_URL }}{{ teacher1.image }}"/>
                                </dt>
                            </a>
                            <dd>
                                <a href="{% url 'orgs:teacher_detail' teacher1.id %}">
                                    <h1 title="{{ teacher1.name }}">{{ teacher1.name }}</h1>
                                </a>
                                <p>工作年限：<span>{{ teacher1.work_year }}年</span></p>
                            </dd>
                        </dl>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
	</div>
</section>
{% endblock %}
{% block myjs %}
    <script>
        $(function () {
            $('#jsLeftBtn').click(function () {
                var loveid = {{ teacher.id }};
                var lovetype = 3;
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_love' %}',
                    data:{
                        lovetype:lovetype,
                        loveid:loveid
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            $('#jsLeftBtn').text(callback.msg)
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            });
            $('#jsRightBtn').click(function () {
                var loveid = {{ teacher.work_company.id }};
                var lovetype = 1;
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_love' %}',
                    data:{
                        lovetype:lovetype,
                        loveid:loveid
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            $('#jsRightBtn').text(callback.msg)
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            });
        })
    </script>
{% endblock %}