code/wfedu/GuLiEdu/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
import xadmin
from users.views import index

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^orgs/', include('orgs.urls', namespace='orgs')),
    url(r'^operations/', include('operations.urls', namespace='operations')),
    url(r'^$',index,name='index')
]

handler404 = 'users.views.handler_404'
handler500 = 'users.views.handler_500'

code/wfedu/apps/courses/urls.py
from django.conf.urls import url
from .views import course_list,course_detail,course_video,course_comment
urlpatterns = [
    url(r'^course_list/$',course_list,name='course_list'),
    url(r'^course_detail/(\d+)/$', course_detail, name='course_detail'),
    url(r'^course_video/(\d+)/$', course_video, name='course_video'),
    url(r'^course_comment/(\d+)/$', course_comment, name='course_comment'),
]

code/wfedu/apps/operations/urls.py
from django.conf.urls import url
from .views import user_ask,user_love,user_comment,user_deletelove
urlpatterns = [
    url(r'^user_ask/$',user_ask,name='user_ask'),
    url(r'^user_love/$',user_love,name='user_love'),
    url(r'^user_deletelove/$',user_deletelove,name='user_deletelove'),
    url(r'^user_comment/$', user_comment, name='user_comment')
]

code/wfedu/apps/orgs/urls.py
from django.conf.urls import url
from .views import org_list,org_detail,org_detail_course,org_detail_desc,org_detail_teacher,teacher_list,teacher_detail

urlpatterns = [
    url(r'^org_list/$',org_list,name='org_list'),
    url(r'^org_detail/(\d+)/$', org_detail, name='org_detail'),
    url(r'^org_detail_course/(\d+)/$', org_detail_course, name='org_detail_course'),
    url(r'^org_detail_desc/(\d+)/$', org_detail_desc, name='org_detail_desc'),
    url(r'^org_detail_teacher/(\d+)/$', org_detail_teacher, name='org_detail_teacher'),

    url(r'^teacher_list/$',teacher_list,name='teacher_list'),
    url(r'^teacher_detail/(\d+)/$', teacher_detail, name='teacher_detail'),
]

code/wfedu/apps/users/urls.py
from django.conf.urls import url
from .views import user_register,UserLoginView,user_logout,user_active,user_forget,user_reset,user_info,user_changeimage,user_changeinfo,user_changeemail,user_resetemail,user_course,user_loveteacher,user_loveorg,user_lovecourse,user_message,user_deletemessage
urlpatterns = [
    url(r'^user_register/$',user_register,name='user_register'),
    url(r'^user_login/$', UserLoginView.as_view(), name='user_login'),
    url(r'^user_logout/$', user_logout, name='user_logout'),
    url(r'^user_active/(\w+)/$', user_active, name='user_active'),

    url(r'^user_forget/$', user_forget, name='user_forget'),
    url(r'^user_reset/(\w+)/$', user_reset, name='user_reset'),

    url(r'^user_info/$',user_info,name='user_info'),

    url(r'^user_changeimage/$',user_changeimage,name='user_changeimage'),
    url(r'^user_changeinfo/$', user_changeinfo, name='user_changeinfo'),
    url(r'^user_changeemail/$',user_changeemail,name='user_changeemail'),
    url(r'^user_resetemail/$', user_resetemail, name='user_resetemail'),

    url(r'^user_course/$',user_course,name='user_course'),
    url(r'^user_loveorg/$', user_loveorg, name='user_loveorg'),
    url(r'^user_loveteacher/$', user_loveteacher, name='user_loveteacher'),
    url(r'^user_lovecourse/$', user_lovecourse, name='user_lovecourse'),

    url(r'^user_message/$', user_message, name='user_message'),
    url(r'^user_deletemessage/$', user_deletemessage, name='user_deletemessage'),

]

code/wfedu/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

code/wfedu/apps/courses/models.py
from django.db import models
from datetime import datetime
from orgs.models import OrgInfo,TeacherInfo
# Create your models here.
class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/',max_length=200,verbose_name="课程封面")
    name = models.CharField(max_length=20,verbose_name="课程名称")
    study_time = models.IntegerField(default=0,verbose_name="学习时长")
    study_num = models.IntegerField(default=0,verbose_name="学习人数")
    level = models.CharField(choices=(('gj','高级'),('zj','中级'),('cj','初级')),max_length=5,verbose_name="课程 难度",default='cj')
    love_num = models.IntegerField(default=0,verbose_name="收藏数")
    click_num = models.IntegerField(default=0,verbose_name="访问量")
    desc = models.CharField(max_length=200,verbose_name="课程简介")
    detail = models.TextField(verbose_name="课程详情")
    category = models.CharField(choices=(('qd','前端开发'),('hd','后端开发')),verbose_name="课程类别",max_length=5)
    course_notice = models.CharField(max_length=200,verbose_name="课程公告")
    course_need = models.CharField(max_length=100,verbose_name="课程须知")
    teacher_tell = models.CharField(max_length=100,verbose_name="老师教导")
    orginfo = models.ForeignKey(OrgInfo,verbose_name="所属机构")
    teacherinfo = models.ForeignKey(TeacherInfo,verbose_name="所属讲师")
    is_banner = models.BooleanField(default=False,verbose_name="是否轮播")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程信息'
        verbose_name_plural = verbose_name

class LessonInfo(models.Model):
    name = models.CharField(max_length=50,verbose_name="章节名称")
    courseinfo = models.ForeignKey(CourseInfo,verbose_name="所属课程")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '章节信息'
        verbose_name_plural = verbose_name


class VideoInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name="视频名称")
    study_time = models.IntegerField(default=0,verbose_name="视频时长")
    url = models.URLField(default='http://www.atguigu.com',verbose_name="视频链接",max_length=200)
    lessoninfo = models.ForeignKey(LessonInfo,verbose_name="所属章节")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '视频信息'
        verbose_name_plural = verbose_name


class SourceInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name="资源名称")
    down_load = models.FileField(upload_to='source/',max_length=200,verbose_name="下载路径")
    courseinfo = models.ForeignKey(CourseInfo,verbose_name="所属课程")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '资源信息'
        verbose_name_plural = verbose_name

code/wfedu/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
# Create your models here.
class UserProfile(AbstractUser):
    image = models.ImageField(upload_to='user/',max_length=200,verbose_name="用户头像",null=True,blank=True)
    nick_name = models.CharField(max_length=20,verbose_name="用户昵称",null=True,blank=True)
    birthday = models.DateField(verbose_name="用户生日",null=True,blank=True)
    gender = models.CharField(choices=(('girl','女'),('boy','男')),max_length=10,verbose_name="用户性别",default='girl')
    address = models.CharField(max_length=200,verbose_name="用户地址",null=True,blank=True)
    phone = models.CharField(max_length=11,verbose_name="用户手机",null=True,blank=True)
    #这个字段控制激活
    is_start = models.BooleanField(default=False,verbose_name="是否激活")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.username

    def get_msg_counter(self):
        from operations.models import UserMessage
        counter = UserMessage.objects.filter(message_man = self.id,message_status=False).count()
        return counter


    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name


class BannerInfo(models.Model):
    image = models.ImageField(upload_to='banner/',verbose_name="轮播图片",max_length=200)
    url = models.URLField(default='http://www.atguigu.com',max_length=200,verbose_name="图片链接")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return str(self.image)

    class Meta:
        verbose_name = '轮播图信息'
        verbose_name_plural = verbose_name


class EmailVerifyCode(models.Model):
    code = models.CharField(max_length=20,verbose_name="邮箱验证码")
    email = models.EmailField(max_length=200,verbose_name="验证码邮箱")
    send_type = models.IntegerField(choices=((1,'register'),(2,'forget'),(3,'change')),verbose_name="验证码类型")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = '邮箱验证码信息'
        verbose_name_plural = verbose_name

code/wfedu/apps/users/forms.py

from django import forms
from captcha.fields import CaptchaField
from .models import UserProfile,EmailVerifyCode

class UserRegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True,min_length=3,max_length=15,error_messages={
        'required':'密码必须填写',
        'min_length':'密码至少3位',
        'max_length':'密码不能超过15位'
    })
    captcha = CaptchaField()



class UserLoginForm(forms.Form):
    username = forms.EmailField(required=True)
    password = forms.CharField(required=True,min_length=3,max_length=15,error_messages={
        'required':'密码必须填写',
        'min_length':'密码至少3位',
        'max_length':'密码不能超过15位'
    })

class UserForgetForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField()

class UserResetForm(forms.Form):
    password = forms.CharField(required=True,min_length=3,max_length=15,error_messages={
        'required':'密码必须填写',
        'min_length':'密码至少3位',
        'max_length':'密码不能超过15位'
    })
    password1 = forms.CharField(required=True,min_length=3,max_length=15,error_messages={
        'required':'密码必须填写',
        'min_length':'密码至少3位',
        'max_length':'密码不能超过15位'
    })

class UserChangeImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']

class UserChangeInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name','gender','address','phone','birthday']



class UserChangeEmailForm(forms.ModelForm):
    class Meta:
        model = EmailVerifyCode
        fields = ['email']

class UserResetEmailForm(forms.ModelForm):
    class Meta:
        model = EmailVerifyCode
        fields = ['email','code']

code/wfedu/templates/users/usercenter-base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block mycss %}
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lq.datetimepick.css' %}"/>
    {% block mycss1 %}{% endblock %}
{% endblock %}

{% block middle %}
    <div class="middle">
        <div class="wp">
            <a href="/"><img class="fl" src="{% static 'images/logo1.png' %}"/></a>
            <h1>我的万锋教育网</h1>
        </div>
    </div>
{% endblock %}

{% block content %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>{% block breach %}{% endblock %}</li>
            </ul>
        </div>
    </section>
    <section>
        <div class="wp list personal_list">
            <div class="left">
                <ul>
                    <li {% if request.path == '/users/user_info/' %} class="active2"{% endif %}><a href="{% url 'users:user_info' %}">个人资料</a></li>
                    <li {% if request.path == '/users/user_course/' %} class="active2"{% endif %}><a href="{% url 'users:user_course' %}">我的课程</a></li>
                    <li {% if request.path|slice:":16" == '/users/user_love' %} class="active2"{% endif %}><a href="{% url 'users:user_loveorg' %}">我的收藏</a></li>
                    <li {% if request.path == '/users/user_message/' %} class="active2"{% endif %}>
                        <a href="{% url 'users:user_message' %}" style="position: relative;">
                            我的消息
                        </a>
                    </li>
                </ul>
            </div>

            {% block right %}
            {% endblock %}

        </div>
    </section>
    {% block dialog %}
        <div class="dialog" id="jsDialog">
            <div class="resetpwdbox dialogbox" id="jsResetDialog">
                <h1>修改密码</h1>
                <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
                <div class="cont">
                    <form id="jsResetPwdForm" autocomplete="off">
                        <div class="box">
                            <span class="word2" >新&nbsp;&nbsp;密  码</span> &nbsp;
                            <input type="password" id="pwd" name="password1" placeholder="6-20位非中文字符"/>
                        </div>
                        <div class="box">
                            <span class="word2" >确定密码</span>
                            <input type="password" id="repwd" name="password2" placeholder="6-20位非中文字符"/>
                        </div>
                        <div class="error btns" id="jsResetPwdTips"></div>
                        <div class="button">
                            <input id="jsResetPwdBtn" type="button" value="提交" />
                        </div>
                        <input type='hidden' name='csrfmiddlewaretoken' value='DaP7IUKm9FA9nELA9YUlYYWpyIDdCiIP' />
                    <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
                    </form>
                </div>
            </div>
            <div class="dialogbox changeemai1 changephone" id="jsChangeEmailDialog">
            <h1>修改邮箱</h1>
            <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
            <p>请输入新的邮箱地址</p>
            <form id="jsChangeEmailForm" autocomplete="off">
                <div class="box">
                    <input class="fl change_email" name="email" id="jsChangeEmail" type="text" placeholder="输入重新绑定的邮箱地址">
                </div>
                <div class="box">
                    <input class="fl email_code" type="text" id="jsChangeEmailCode" name="code" placeholder="输入邮箱验证码">
                    <input class="getcode getting" type="button" id="jsChangeEmailCodeBt" value="获取验证码">
                </div>
                <div class="error btns change_email_tips" id="jsChangeEmailTips" >请输入...</div>
                <div class="button">
                    <input class="changeemai_btn" id="jsChangeEmailBt" type="button" value="完成"/>
                </div>
                <input type='hidden' name='csrfmiddlewaretoken' value='DaP7IUKm9FA9nELA9YUlYYWpyIDdCiIP' />
            <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
            </form>
        </div>
        </div>
        <div class="bg" id="dialogBg"></div>
     {% endblock %}
{% endblock %}

{% block footer %}{% endblock %}

{% block myjs %}
    <script src='{% static 'js/plugins/jquery.upload.js' %}' type='text/javascript'></script>
    <script src="{% static 'js/validate.js' %}" type="text/javascript"></script>
    {% block user %}
        <script src="{% static 'js/deco-user.js' %}"></script>
    {% endblock %}
    <script>
        $(function () {
            $('#jsChangeEmailCodeBt').click(function () {
                var email = $('#jsChangeEmail').val();
                $.ajax({
                    type:'POST',
                    url:'{% url 'users:user_changeemail' %}',
                    data:{
                        email:email,
                        csrfmiddlewaretoken:'{{ csrf_token }}'
                    },
                    success:function (callback) {
                        alert(callback.msg)
                    }
                })
            });
            $('#jsChangeEmailBt').click(function () {
                var email = $('#jsChangeEmail').val();
                var code = $('#jsChangeEmailCode').val();
                $.ajax({
                    type:'POST',
                    url:'{% url 'users:user_resetemail' %}',
                    data:{
                        email:email,
                        code:code,
                        csrfmiddlewaretoken:'{{ csrf_token }}'
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            alert(callback.msg);
                            window.location.href = '{% url 'users:user_login' %}';
                        }else {
                            alert(callback.msg);
                        }

                    }
                })
            })

        })
    </script>
    {% block myjs1 %}{% endblock %}
{% endblock %}



code/wfedu/templates/users/usercenter-fav-course.html
{% extends 'users/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏- 万锋教育网{% endblock %}
{% block breach %}我的收藏{% endblock %}
{% block right %}
     <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:user_loveorg' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:user_loveteacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:user_lovecourse' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in course_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'courses:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'courses:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.study_time }}</i></span>
                                <span class="fr">学习人数：{{ course.study_num }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.orginfo.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}
{% block user %}{% endblock %}
{% block myjs1 %}
    <script>
        $(function () {
            $('.delete-group').click(function () {
                {# prop()用来取元素自带属性的值或者设置值   attr用来取元素自定义的属性的值或者设置值 #}
                var loveid = $(this).attr('data-favid');
                var lovetype = 2;
                var obj = $(this);
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_deletelove' %}',
                    data:{
                        loveid:loveid,
                        lovetype:lovetype
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            {#alert(callback.msg);#}
                            {# 拿到点击对象的祖先节点 当中有类名是des的祖先节点 #}
                            obj.parents('.module1_5').remove()
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}


code/wfedu/templates/users/usercenter-fav-org.html
{% extends 'users/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏- 万锋教育网{% endblock %}
{% block breach %}我的收藏{% endblock %}
{% block right %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:user_loveorg' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:user_loveteacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:user_lovecourse' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                {% for org in org_list %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'orgs:org_detail' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'orgs:org_detail' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>

                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}
{% block user %}{% endblock %}
{% block myjs1 %}
    <script>
        $(function () {
            $('.delete').click(function () {
                {# prop()用来取元素自带属性的值或者设置值   attr用来取元素自定义的属性的值或者设置值 #}
                var loveid = $(this).attr('data-favid');
                var lovetype = 1;
                var obj = $(this);
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_deletelove' %}',
                    data:{
                        loveid:loveid,
                        lovetype:lovetype
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            {#alert(callback.msg);#}
                            {# 拿到点击对象的祖先节点 当中有类名是des的祖先节点 #}
                            obj.parents('.messages').remove()
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}

code/wfedu/templates/users/usercenter-fav-teacher.html
{% extends 'users/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏- 万锋教育网{% endblock %}
{% block breach %}我的收藏{% endblock %}
{% block right %}
     <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:user_loveorg' %}">课程机构</a> </li>
                        <li class="active"><a href="{% url 'users:user_loveteacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:user_lovecourse' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for teacher in teacher_list %}
                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                        {{ teacher.name }}<span class="key">认证教师</span>
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>{{ teacher.work_year }}年</span></li>
                                    <li class="c7">课程数：<span>{{ teacher.courseinfo_set.count }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作公司：<span>{{ teacher.work_company.name }}</span></li>
                                    <li class="c7">公司职位：<span>{{ teacher.work_position }}</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favid="{{ teacher.id }}"></div>
                        </dl>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
{% endblock %}
{% block user %}{% endblock %}
{% block myjs1 %}
    <script>
        $(function () {
            $('.delete').click(function () {
                {# prop()用来取元素自带属性的值或者设置值   attr用来取元素自定义的属性的值或者设置值 #}
                var loveid = $(this).attr('data-favid');
                var lovetype = 3;
                var obj = $(this);
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_deletelove' %}',
                    data:{
                        loveid:loveid,
                        lovetype:lovetype
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            {#alert(callback.msg);#}
                            {# 拿到点击对象的祖先节点 当中有类名是des的祖先节点 #}
                            obj.parents('.butler_list').remove()
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}


code/wfedu/templates/users/usercenter-message.html
{% extends 'users/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的消息- 万锋教育网{% endblock %}
{% block breach %}我的消息{% endblock %}
{% block right %}
     <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的消息</h1>
			</div>

		</div>
		<div class="personal_des permessage">
			<div class="head">
				<ul class="tab_header messagehead">
					<li class="active"><a href="{% url 'users:user_message' %}">个人消息</a> </li>
				</ul>


			</div>
			<div class="messagelist">
                {% for msg in msg_list %}
                    <div class="messages" msg-id="{{ msg.id }}">
                        <div class="fr">
                            <div class="top"><span class="fl time">{{ msg.add_time }}</span><span class="fr btn foldbtn"></span></div>
                            <p {% if not msg.message_status %}style="color: hotpink" {% endif %} >
                                {{ msg.message_content }}
                            </p>
                        </div>
                    </div>
                {% endfor %}
			</div>


{#			<div class="pageturn pagerright">#}
{#                <ul class="pagelist">#}
{#                #}
{##}
{#                #}
{#                    #}
{#                        #}
{#                            <li class="active"><a href="?page=1">1</a></li>#}
{#                        #}
{#                    #}
{#                #}
{#                #}
{##}
{#            </ul>#}
{#            </div>#}
		</div>

	</div>
{% endblock %}
{% block user %}{% endblock %}
{% block myjs1 %}
    <script>
        $(function () {
            $('.messages').click(function () {
                var delete_id = $(this).attr('msg-id');
                $.ajax({
                    type:"GET",
                    url:"{% url 'users:user_deletemessage' %}",
                    data:{
                        delete_id:delete_id
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            window.location.reload()
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}
