code/wfedu/GuLiEdu/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
import xadmin
from users.views import index

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^orgs/', include('orgs.urls', namespace='orgs')),
    url(r'^operations/', include('operations.urls', namespace='operations')),
    url(r'^$',index,name='index')
]

handler404 = 'users.views.handler_404'
handler500 = 'users.views.handler_500'

code/wfedu/apps/courses/urls.py
from django.conf.urls import url
from .views import course_list,course_detail,course_video,course_comment
urlpatterns = [
    url(r'^course_list/$',course_list,name='course_list'),
    url(r'^course_detail/(\d+)/$', course_detail, name='course_detail'),
    url(r'^course_video/(\d+)/$', course_video, name='course_video'),
    url(r'^course_comment/(\d+)/$', course_comment, name='course_comment'),
]

code/wfedu/apps/operations/urls.py
from django.conf.urls import url
from .views import user_ask,user_love,user_comment,user_deletelove
urlpatterns = [
    url(r'^user_ask/$',user_ask,name='user_ask'),
    url(r'^user_love/$',user_love,name='user_love'),
    url(r'^user_deletelove/$',user_deletelove,name='user_deletelove'),
    url(r'^user_comment/$', user_comment, name='user_comment')
]

code/wfedu/apps/orgs/urls.py
from django.conf.urls import url
from .views import org_list,org_detail,org_detail_course,org_detail_desc,org_detail_teacher,teacher_list,teacher_detail

urlpatterns = [
    url(r'^org_list/$',org_list,name='org_list'),
    url(r'^org_detail/(\d+)/$', org_detail, name='org_detail'),
    url(r'^org_detail_course/(\d+)/$', org_detail_course, name='org_detail_course'),
    url(r'^org_detail_desc/(\d+)/$', org_detail_desc, name='org_detail_desc'),
    url(r'^org_detail_teacher/(\d+)/$', org_detail_teacher, name='org_detail_teacher'),

    url(r'^teacher_list/$',teacher_list,name='teacher_list'),
    url(r'^teacher_detail/(\d+)/$', teacher_detail, name='teacher_detail'),
]

code/wfedu/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

code/wfedu/apps/courses/models.py
from django.db import models
from datetime import datetime
from orgs.models import OrgInfo,TeacherInfo
# Create your models here.
class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/',max_length=200,verbose_name="课程封面")
    name = models.CharField(max_length=20,verbose_name="课程名称")
    study_time = models.IntegerField(default=0,verbose_name="学习时长")
    study_num = models.IntegerField(default=0,verbose_name="学习人数")
    level = models.CharField(choices=(('gj','高级'),('zj','中级'),('cj','初级')),max_length=5,verbose_name="课程 难度",default='cj')
    love_num = models.IntegerField(default=0,verbose_name="收藏数")
    click_num = models.IntegerField(default=0,verbose_name="访问量")
    desc = models.CharField(max_length=200,verbose_name="课程简介")
    detail = models.TextField(verbose_name="课程详情")
    category = models.CharField(choices=(('qd','前端开发'),('hd','后端开发')),verbose_name="课程类别",max_length=5)
    course_notice = models.CharField(max_length=200,verbose_name="课程公告")
    course_need = models.CharField(max_length=100,verbose_name="课程须知")
    teacher_tell = models.CharField(max_length=100,verbose_name="老师教导")
    orginfo = models.ForeignKey(OrgInfo,verbose_name="所属机构")
    teacherinfo = models.ForeignKey(TeacherInfo,verbose_name="所属讲师")
    is_banner = models.BooleanField(default=False,verbose_name="是否轮播")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程信息'
        verbose_name_plural = verbose_name

class LessonInfo(models.Model):
    name = models.CharField(max_length=50,verbose_name="章节名称")
    courseinfo = models.ForeignKey(CourseInfo,verbose_name="所属课程")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '章节信息'
        verbose_name_plural = verbose_name


class VideoInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name="视频名称")
    study_time = models.IntegerField(default=0,verbose_name="视频时长")
    url = models.URLField(default='http://www.atguigu.com',verbose_name="视频链接",max_length=200)
    lessoninfo = models.ForeignKey(LessonInfo,verbose_name="所属章节")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '视频信息'
        verbose_name_plural = verbose_name


class SourceInfo(models.Model):
    name = models.CharField(max_length=50, verbose_name="资源名称")
    down_load = models.FileField(upload_to='source/',max_length=200,verbose_name="下载路径")
    courseinfo = models.ForeignKey(CourseInfo,verbose_name="所属课程")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '资源信息'
        verbose_name_plural = verbose_name

code/wfedu/apps/operations/models.py
from django.db import models
from datetime import datetime
from users.models import UserProfile
from courses.models import CourseInfo
# Create your models here.
class UserAsk(models.Model):
    name = models.CharField(max_length=30,verbose_name="姓名")
    phone = models.CharField(max_length=11,verbose_name="手机")
    course = models.CharField(max_length=20,verbose_name="课程")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '咨询信息'
        verbose_name_plural = verbose_name

class UserLove(models.Model):
    love_man = models.ForeignKey(UserProfile,verbose_name="收藏用户")
    love_id = models.IntegerField(verbose_name="收藏id")
    love_type = models.IntegerField(choices=((1,'机构'),(2,'课程'),(3,'讲师')),verbose_name="收藏类别")
    love_status = models.BooleanField(default=False,verbose_name="收藏状态")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="收藏时间")

    def __str__(self):
        return self.love_man.username

    class Meta:
        verbose_name = '收藏信息'
        verbose_name_plural = verbose_name

class UserCourse(models.Model):
    study_man = models.ForeignKey(UserProfile, verbose_name="学习用户")
    study_course = models.ForeignKey(CourseInfo,verbose_name="学习课程")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="学习时间")

    def __str__(self):
        return self.study_man.username

    class Meta:
        unique_together = ('study_man','study_course')
        verbose_name = '用户学习课程信息'
        verbose_name_plural = verbose_name


class UserComment(models.Model):
    comment_man = models.ForeignKey(UserProfile, verbose_name="评论用户")
    comment_course = models.ForeignKey(CourseInfo, verbose_name="评论课程")
    comment_content = models.CharField(max_length=300,verbose_name="评论内容")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="评论时间")

    def __str__(self):
        return self.comment_content

    class Meta:
        verbose_name = '用户评论课程信息'
        verbose_name_plural = verbose_name

class UserMessage(models.Model):
    message_man = models.IntegerField(default=0,verbose_name="消息用户")
    message_content = models.CharField(max_length=200,verbose_name="消息内容")
    message_status = models.BooleanField(default=False,verbose_name="消息状态")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.message_content

    class Meta:
        verbose_name = '用户消息信息'
        verbose_name_plural = verbose_name

code/wfedu/apps/orgs/models.py
from django.db import models
from datetime import datetime
from DjangoUeditor.models import UEditorField
# Create your models here.
class CityInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="城市名称")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '城市信息'
        verbose_name_plural = verbose_name


class OrgInfo(models.Model):
    image = models.ImageField(upload_to='org/',max_length=200,verbose_name="机构封面")
    name = models.CharField(max_length=20,verbose_name="机构名称")
    course_num = models.IntegerField(default=0,verbose_name="课程数")
    study_num = models.IntegerField(default=0,verbose_name="学习人数")
    address = models.CharField(max_length=200,verbose_name="机构地址")
    desc = models.CharField(max_length=200,verbose_name="机构简介")
    detail = UEditorField(verbose_name='机构详情',
	                         width=700,
	                         height=400,
	                         toolbars='full',
	                         imagePath='ueditor/images/',
	                         filePath='ueditor/files/',
	                         upload_settings={'imageMaxSizing':1024000},
	                         default='')

    love_num = models.IntegerField(default=0,verbose_name="收藏数")
    click_num = models.IntegerField(default=0,verbose_name="访问量")
    category = models.CharField(choices=(('pxjg','培训机构'),('gx','高校'),('gr','个人')),max_length=10,verbose_name="机构类别")
    cityinfo = models.ForeignKey(CityInfo,verbose_name="所在城市")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机构信息'
        verbose_name_plural = verbose_name


class TeacherInfo(models.Model):
    image = models.ImageField(upload_to='teacher/', max_length=200, verbose_name="讲师头像")
    name = models.CharField(max_length=20,verbose_name="讲师姓名")
    work_year = models.IntegerField(default=3,verbose_name="工作年限")
    work_position = models.CharField(max_length=20,verbose_name="工作职位")
    work_style = models.CharField(max_length=20,verbose_name="教学特点")
    work_company = models.ForeignKey(OrgInfo,verbose_name="所属机构")
    age = models.IntegerField(default=30,verbose_name="讲师年龄")
    gender = models.CharField(choices=(('boy','男'),('girl','女')),max_length=10,verbose_name="讲师性别",default='boy')
    love_num = models.IntegerField(default=0, verbose_name="收藏数")
    click_num = models.IntegerField(default=0, verbose_name="访问量")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '讲师信息'
        verbose_name_plural = verbose_name


code/wfedu/apps/courses/views.py
from django.shortcuts import render
from .models import CourseInfo
from django.core.paginator import PageNotAnInteger,EmptyPage,Paginator
from operations.models import UserLove,UserCourse
from django.db.models import Q
from tools.decorators import login_decorator

# from django.contrib.auth.decorators import login_required
# Create your views here.

def course_list(request):
    all_courses = CourseInfo.objects.all()
    recommend_courses = all_courses.order_by('-add_time')[:3]

    # 全局搜索功能的过滤
    keyword = request.GET.get('keyword', '')
    if keyword:
        all_courses = all_courses.filter(
            Q(name__icontains=keyword) | Q(desc__icontains=keyword) | Q(detail__icontains=keyword))

    sort = request.GET.get('sort','')
    if sort:
        all_courses = all_courses.order_by('-'+sort)

    # 分页功能
    pagenum = request.GET.get('pagenum', '')
    pa = Paginator(all_courses, 3)
    try:
        pages = pa.page(pagenum)
    except PageNotAnInteger:
        pages = pa.page(1)
    except EmptyPage:
        pages = pa.page(pa.num_pages)

    return render(request,'courses/course-list.html',{
        'all_courses':all_courses,
        'pages':pages,
        'recommend_courses':recommend_courses,
        'sort':sort,
        'keyword':keyword
    })

def course_detail(request,course_id):
    if course_id:
        course = CourseInfo.objects.filter(id = int(course_id))[0]
        relate_courses = CourseInfo.objects.filter(category=course.category).exclude(id=int(course_id))[:2]

        course.click_num += 1
        course.save()

        #lovecourse和loveorg 用来存储用户收藏这个东西的状态，在模板当中根据这个状态来确定页面加载时候，显示的是收藏还是取消收藏
        lovecourse = False
        loveorg = False
        if request.user.is_authenticated():
            love = UserLove.objects.filter(love_id=int(course_id),love_type=2,love_status=True,love_man=request.user)
            if love:
                lovecourse = True
            love1 = UserLove.objects.filter(love_id=course.orginfo.id,love_type=1,love_status=True,love_man=request.user)
            if love1:
                loveorg = True

        return render(request,'courses/course-detail.html',{
            'course':course,
            'relate_courses':relate_courses,
            'lovecourse':lovecourse,
            'loveorg':loveorg
        })

@login_decorator
def course_video(request,course_id):
    if course_id:
        course = CourseInfo.objects.filter(id = int(course_id))[0]

        #当用户点击开始学习以后，代表这个用户学习了这个课程，我们需要去判断用户学习课程的表当中有没有学习这门课程的记录，如果没有，需要给加上这条记录，代表用户学习了这门课程
        usercourse_list = UserCourse.objects.filter(study_man=request.user,study_course=course)
        if not usercourse_list:
            a = UserCourse()
            a.study_man = request.user
            a.study_course = course
            a.save()
            course.study_num += 1
            course.save()


            #第一步：从学习课程的表当中查找当前这个人学习的所有的课程,出去新学的这门课程
            usercourse_list = UserCourse.objects.filter(study_man=request.user).exclude(study_course=course)
            course_list = [usercourse.study_course for usercourse in usercourse_list]
            #第二步：根据拿到的所有课程，找到这个用户学过课程的机构
            org_list = list(set([course1.orginfo for course1 in course_list]))
            #第三步：判断当前所学的课程机构，是不是在这个用户之前所学的机构当中，如果不在，那么机构的学习人数+1
            if course.orginfo not in org_list:
                course.orginfo.study_num += 1
                course.orginfo.save()





        #学过该课的同学还学过什么课程
        #第一步：我们需要从中间表用户课程表当中找到学过该课的所有对象
        usercourse_list = UserCourse.objects.filter(study_course=course)

        #第二步：根据找到的用户学习课程列表，遍历拿到所有学习过这门课程的用户列表
        user_list = [usercourse.study_man for usercourse in usercourse_list]

        #第三步：再根据找到的用户，从中间用户学习课程表当中，找到所有用户学习其它课程的 整个对象,需要用到exclude去除当前学过的这个课程对象
        usercourse_list = UserCourse.objects.filter(study_man__in=user_list).exclude(study_course=course)

        #第四步：从获取到的用户课程列表当中，拿到我们需要的其它课程
        course_list = list(set([usercourse.study_course for usercourse in usercourse_list]))



        return render(request,'courses/course-video.html',{
            'course':course,
            'course_list':course_list
        })

def course_comment(request,course_id):
    if course_id:
        course = CourseInfo.objects.filter(id = int(course_id))[0]
        all_comments = course.usercomment_set.all()[:10]

        # 学过该课的同学还学过什么课程
        # 第一步：我们需要从中间表用户课程表当中找到学过该课的所有对象
        usercourse_list = UserCourse.objects.filter(study_course=course)

        # 第二步：根据找到的用户学习课程列表，遍历拿到所有学习过这门课程的用户列表
        user_list = [usercourse.study_man for usercourse in usercourse_list]

        # 第三步：再根据找到的用户，从中间用户学习课程表当中，找到所有用户学习其它课程的 整个对象,需要用到exclude去除当前学过的这个课程对象
        usercourse_list = UserCourse.objects.filter(study_man__in=user_list).exclude(study_course=course)

        # 第四步：从获取到的用户课程列表当中，拿到我们需要的其它课程
        course_list = list(set([usercourse.study_course for usercourse in usercourse_list]))

        return render(request,'courses/course-comment.html',{
            'course':course,
            'all_comments':all_comments,
            'course_list':course_list
        })

code/wfedu/templates/courses/course-detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}公开课详情 - 谷粒教育网{% endblock %}
{% block content %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="/">首页</a>></li>
                <li><a href="{% url 'courses:course_list' %}">公开课程</a>></li>
				<li>课程详情</li>
			</ul>
		</div>
	</div>
</section>
    <section>
	<div class="wp">
		<div class="groupPurchase_detail detail">
			<div class="toppro">
				<div class="left">
					<div class="picbox">
						<div class="tb-booth tb-pic">
							<img width="440" height="445" src="{{ MEDIA_URL }}{{ course.image }}" class="jqzoom" />
						</div>

					</div>
					<div class="des">
						<h1 title="{{ course.name }}">{{ course.name }}</h1>
						<span class="key">{{ course.desc }}</span>
						<div class="prize">
							<span class="fl">难度：
                            <i class="key">
                                 {% if course.level == 'cj' %}
                                        初级
                                 {% elif course.level == 'zj' %}
                                        中级
                                 {% else %}
                                        高级
                                 {% endif %}
                            </i></span>
							<span class="fr">学习人数：12</span>
						</div>
						<ul class="parameter">
							<li><span class="pram word3">时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;长：</span><span>{{ course.study_time }}</span></li>
                            <li><span class="pram word3">章&nbsp;节&nbsp;数：</span><span>{{ course.lessoninfo_set.count }}</span></li>
                            <li>
                                <span class="pram word3">课程类别：</span>
                                <span title="">
                                 {% if course.category == 'qd' %}
                                        前端开发
                                 {% else %}
                                        后端开发
                                 {% endif %}
                                </span>
                            </li>
							<li class="piclist"><span class="pram word4">学习用户：</span>
                                    {% for usercourse in course.usercourse_set.all|slice:":6" %}
                                    <span class="pic"><img width="40" height="40" src="{{ MEDIA_URL }}{{ usercourse.study_man.image }}"/></span>
                                    {% endfor %}
							</li>
						</ul>
						<div class="btns">
							<div class="btn colectgroupbtn"  id="jsLeftBtn">
                                  {% if lovecourse %}取消收藏{% else %}收藏{% endif %}
                            </div>
                                <div class="buy btn"><a style="color: white" href="{% url 'courses:course_video' course.id %}">开始学习</a></div>
						</div>
					</div>
				</div>
				<div class="right">
					<div class="head">
						<h1>授课机构</h1>
						<p>世界名校，课程权威</p>
					</div>
					<div class="pic">
                        <a href="{% url 'orgs:org_detail' course.orginfo.id %}">
                            <img width="150" height="80" src="{{ MEDIA_URL }}{{ course.orginfo.image }}"/>
                        </a>
                    </div>
					<a href="{% url 'orgs:org_detail' course.orginfo.id %}">
                        <h2 class="center" title="{{ course.orginfo.name }}">{{ course.orginfo.name }}</h2>
                    </a>
					<div class="btn  notlogin" data-favid="14" id="jsRightBtn">
                         {% if loveorg %}取消收藏{% else %}收藏{% endif %}
                    </div>
					<div class="clear">
						<ul>
                            <li>
                                <span>课 &nbsp;程&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   {{ course.orginfo.course_num }}</span>
                            </li>
                            <li>
                                <span>教 &nbsp;师&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  {{ course.orginfo.teacherinfo_set.count }}</span>
                            </li>
							<li>所在地区：&nbsp;&nbsp;{{ course.orginfo.cityinfo.name }}</li>
							<li>认&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;证&nbsp;:
                                &nbsp;&nbsp;
								    <img title="金牌机构" src="{% static 'images/gold.png' %}"/>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
    <section>
	<div class="wp">
		<div class="list groupPurchase_detail_pro">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active">课程详情</li>
					</ul>
				</div>
				<div class="tab_cont tab_cont1">

					<p>
                        {{ course.detail }}
                    </p>

				</div>
			</div>
			<div class="right layout">
				<div class="head">相关课程推荐</div>
                <div class="group_recommend">
                    {% for relate in relate_courses %}
                        <dl>
                            <dt>
                                <a target="_blank" href="{% url 'courses:course_detail' relate.id %}">
                                    <img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ relate.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <a target="_blank" href="{% url 'courses:course_detail' relate.id %}"><h2> {{ relate.name }}</h2></a>
                                <span class="fl">学习时长：<i class="key">{{ relate.study_time }}</i></span>
                            </dd>
                        </dl>
                    {% endfor %}
                </div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

{% block myjs %}
    <script>
        $(function () {
            $('#jsLeftBtn').click(function () {
                var loveid = {{ course.id }};
                var lovetype = 2;
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_love' %}',
                    data:{
                        lovetype:lovetype,
                        loveid:loveid
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            $('#jsLeftBtn').text(callback.msg)
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            });
            $('#jsRightBtn').click(function () {
                var loveid = {{ course.orginfo.id }};
                var lovetype = 1;
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_love' %}',
                    data:{
                        lovetype:lovetype,
                        loveid:loveid
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            $('#jsRightBtn').text(callback.msg)
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            });
        })
    </script>
{% endblock %}

code/wfedu/templates/courses/course-list.html
{% extends 'base.html' %}
{% block title %}
    公开课列表 - 万峰教育网
{% endblock %}

{% block content %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
    <section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li {% if sort == '' %}class="active"{% endif %}><a href="?sort=">最新 </a></li>
						<li {% if sort == 'click_num' %}class="active"{% endif %}><a href="?sort=click_num">最热门</a></li>
						<li {% if sort == 'study_num' %}class="active"{% endif %}><a href="?sort=study_num">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">
                        {% for course in pages %}
                            <div class="box">
                                <a href="{% url 'courses:course_detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:course_detail' course.id %}">
                                        <h2>{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.study_time }}</i></span>
                                    <span class="fr">学习人数：{{ course.study_num }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="{% url 'courses:course_detail' course.id %}"><span class="fl">来自{{ course.orginfo.name }}</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{ course.love_num }}
                                    </span>
                                </div>
                            </div>
                        {% endfor %}
					</div>
                    <div class="pageturn">
            <ul class="pagelist">
                {% if pages.has_previous %}
                <li class="long"><a href="?pagenum={{ pages.previous_page_number }}&sort={{ sort }}&keyword={{ keyword }}">上一页</a></li>
                {% endif %}

                {% for num in pages.paginator.page_range %}
                <li {% if num == pages.number %}class="active"{% endif %}><a href="?pagenum={{ num }}&sort={{ sort }}&keyword={{ keyword }}">{{ num }}</a></li>
                {% endfor %}

                {% if pages.has_next %}
                <li class="long"><a href="?pagenum={{ pages.next_page_number }}&sort={{ sort }}&keyword={{ keyword }}">下一页</a></li>
                {% endif %}
            </ul>
        </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">
                {% for course in recommend_courses %}
                    <dl>
						<dt>
							<a target="_blank" href="{% url 'courses:course_detail' course.id %}">
								<img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href="{% url 'courses:course_detail' course.id %}"><h2> {{ course.name }}</h2></a>
							<span class="fl">难度：
                                <i class="key">
                                
                                    {% if course.level == 'cj' %}
                                        初级
                                    {% elif course.level == 'zj' %}
                                        中级
                                    {% else %}
                                        高级
                                    {% endif %}

                                </i></span>
						</dd>
					</dl>
                {% endfor %}
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}